from sqlalchemy import Boolean, Column, Integer, String, Text, Numeric, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from database.connection import Base

class FinalRanking(Base):
    __tablename__ = "final_rankings"

    ranking_id = Column(Integer, primary_key=True, autoincrement=True)
    application_id = Column(Integer, ForeignKey("applications.application_id"), nullable=False, unique=True)
    posting_id = Column(Integer, ForeignKey("job_postings.posting_id"), nullable=False)
    semantic_score = Column(Numeric(6, 2), nullable=True)
    assessment_score = Column(Numeric(6, 2), nullable=True)
    technical_interview_score = Column(Numeric(6, 2), nullable=True)
    hr_interview_score = Column(Numeric(6, 2), nullable=True)
    weighted_total_score = Column(Numeric(6, 2), nullable=True)
    final_rank = Column(Integer, nullable=True)
    final_recommendation = Column(String(100), nullable=True)
    final_status = Column(String(50), nullable=True)
    # Red-flag: CV #1 but failed live technical interview
    red_flag = Column(Boolean, default=False, nullable=False)
    red_flag_reason = Column(Text, nullable=True)
    # Cross-phase SHAP explanation
    shap_json    = Column(Text, nullable=True)  # JSON {"screening": φ, "assessment": φ, "hr_interview": φ}
    shap_summary = Column(Text, nullable=True)  # human-readable cross-phase narrative
    # Probabilistic risk score (0-1) from sigmoid RF-1/RF-2 model
    risk_score   = Column(Numeric(6, 4), nullable=True)
    # Full per-candidate narrative generated by generate_final_candidate_summary()
    summary      = Column(Text, nullable=True)
    generated_at = Column(DateTime, server_default=func.now())

    application = relationship("Application", back_populates="final_ranking")
    posting = relationship("JobPosting", back_populates="final_rankings")
