"""initial_schema

Revision ID: 462c07477351
Revises: 
Create Date: 2026-03-11 21:56:17.424387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '462c07477351'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('assessment_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('candidate_cvs',
    sa.Column('cv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('cv_id')
    )
    op.create_table('recruiters',
    sa.Column('recruiter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('recruiter_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessment_template_questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.template_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('cv_educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['candidate_cvs.cv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['candidate_cvs.cv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['candidate_cvs.cv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['candidate_cvs.cv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requisitions',
    sa.Column('requisition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('remote_available', sa.Boolean(), nullable=True),
    sa.Column('min_years_experience', sa.Integer(), nullable=True),
    sa.Column('max_years_experience', sa.Integer(), nullable=True),
    sa.Column('min_education_level', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('key_responsibilities', sa.Text(), nullable=True),
    sa.Column('full_job_description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('min_salary_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_salary_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('posting_start_date', sa.Date(), nullable=True),
    sa.Column('cv_collection_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], ),
    sa.PrimaryKeyConstraint('requisition_id')
    )
    op.create_table('hr_interview_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('ai_feedback_level', sa.String(length=50), nullable=True),
    sa.Column('scoring_system', sa.String(length=100), nullable=True),
    sa.Column('candidates_to_advance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('requisition_id')
    )
    op.create_table('job_postings',
    sa.Column('posting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('total_applications', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('posting_id'),
    sa.UniqueConstraint('requisition_id')
    )
    op.create_table('posting_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('platform_post_title', sa.Text(), nullable=True),
    sa.Column('platform_post_content', sa.Text(), nullable=True),
    sa.Column('platform_post_format', sa.String(length=50), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisition_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisition_required_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_assessment_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('assessment_type', sa.String(length=100), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('candidates_to_advance', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('assessment_language', sa.String(length=50), nullable=True),
    sa.Column('sample_task', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.template_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('requisition_id')
    )
    op.create_table('technical_interview_configs',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('ai_feedback_level', sa.String(length=50), nullable=True),
    sa.Column('scoring_system', sa.String(length=100), nullable=True),
    sa.Column('candidates_to_advance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.requisition_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('requisition_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('current_pipeline_stage', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['cv_id'], ['candidate_cvs.cv_id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.posting_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('posting_id', 'candidate_id', name='uq_application_posting_candidate')
    )
    op.create_table('hr_interview_criteria',
    sa.Column('criterion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('criterion_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['hr_interview_configs.config_id'], ),
    sa.PrimaryKeyConstraint('criterion_id')
    )
    op.create_table('interview_evaluation_criteria',
    sa.Column('criterion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('criterion_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('weight_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['technical_interview_configs.config_id'], ),
    sa.PrimaryKeyConstraint('criterion_id')
    )
    op.create_table('candidate_assessments',
    sa.Column('assessment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['technical_assessment_configs.config_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.template_id'], ),
    sa.PrimaryKeyConstraint('assessment_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('final_rankings',
    sa.Column('ranking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('semantic_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('assessment_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('technical_interview_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hr_interview_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weighted_total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('final_recommendation', sa.String(length=100), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.posting_id'], ),
    sa.PrimaryKeyConstraint('ranking_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('hr_interview_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overall_performance', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['hr_interview_configs.config_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('pipeline_stage_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('semantic_analysis_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('match_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_insights', sa.Text(), nullable=True),
    sa.Column('recommendation_summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('rank_in_pool', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('technical_interview_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overall_performance', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['technical_interview_configs.config_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('assessment_answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('candidate_answer', sa.Text(), nullable=True),
    sa.Column('score_awarded', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['candidate_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_template_questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('assessment_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('rank_in_pool', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['candidate_assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('hr_interview_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('interview_summary', sa.Text(), nullable=True),
    sa.Column('detailed_assessment', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('rank_in_pool', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['hr_interview_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('hr_interview_scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['hr_interview_criteria.criterion_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['hr_interview_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('semantic_matched_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['semantic_analysis_reports.report_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_interview_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('interview_summary', sa.Text(), nullable=True),
    sa.Column('detailed_assessment', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('rank_in_pool', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['technical_interview_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('technical_interview_scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['interview_evaluation_criteria.criterion_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['technical_interview_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.drop_table('company_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_test_pkey'))
    )
    op.drop_table('technical_interview_scores')
    op.drop_table('technical_interview_reports')
    op.drop_table('semantic_matched_skills')
    op.drop_table('hr_interview_scores')
    op.drop_table('hr_interview_reports')
    op.drop_table('assessment_reports')
    op.drop_table('assessment_answers')
    op.drop_table('technical_interview_sessions')
    op.drop_table('semantic_analysis_reports')
    op.drop_table('pipeline_stage_logs')
    op.drop_table('hr_interview_sessions')
    op.drop_table('final_rankings')
    op.drop_table('candidate_assessments')
    op.drop_table('interview_evaluation_criteria')
    op.drop_table('hr_interview_criteria')
    op.drop_table('applications')
    op.drop_table('technical_interview_configs')
    op.drop_table('technical_assessment_configs')
    op.drop_table('requisition_required_skills')
    op.drop_table('requisition_languages')
    op.drop_table('posting_platforms')
    op.drop_table('job_postings')
    op.drop_table('hr_interview_configs')
    op.drop_table('job_requisitions')
    op.drop_table('cv_skills')
    op.drop_table('cv_projects')
    op.drop_table('cv_experiences')
    op.drop_table('cv_educations')
    op.drop_table('assessment_template_questions')
    op.drop_table('recruiters')
    op.drop_table('candidate_cvs')
    op.drop_table('assessment_templates')
    op.drop_table('companies')
    op.drop_table('candidates')
    # ### end Alembic commands ###
