"""initial_schema_v1

Revision ID: 71c8c1f3853d
Revises: 47463f4ad0b2
Create Date: 2026-04-26 21:30:38.324621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c8c1f3853d'
down_revision: Union[str, None] = '47463f4ad0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_candidate_id'), table_name='assessment_leaderboards')
    op.drop_index(op.f('ix_leaderboard_jr_id'), table_name='assessment_leaderboards')
    op.drop_index(op.f('ix_jr_processing_status'), table_name='job_requisitions')
    op.drop_index(op.f('ix_tis_room_name'), table_name='technical_interview_sessions')
    op.drop_constraint(op.f('uq_tis_room_name'), 'technical_interview_sessions', type_='unique')
    op.create_index(op.f('ix_technical_interview_sessions_room_name'), 'technical_interview_sessions', ['room_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_interview_sessions_room_name'), table_name='technical_interview_sessions')
    op.create_unique_constraint(op.f('uq_tis_room_name'), 'technical_interview_sessions', ['room_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tis_room_name'), 'technical_interview_sessions', ['room_name'], unique=False)
    op.create_index(op.f('ix_jr_processing_status'), 'job_requisitions', ['processing_status'], unique=False)
    op.create_index(op.f('ix_leaderboard_jr_id'), 'assessment_leaderboards', ['jr_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_candidate_id'), 'assessment_leaderboards', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
