"""add assessment deadline and pool report

Revision ID: d3c438a1516e
Revises: 2d76b25cce55
Create Date: 2026-04-18 21:11:50.076097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c438a1516e'
down_revision: Union[str, None] = '2d76b25cce55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company_social_auth', ['company_id'])
    op.drop_constraint(op.f('company_social_auth_company_id_fkey'), 'company_social_auth', type_='foreignkey')
    op.create_foreign_key(None, 'company_social_auth', 'companies', ['company_id'], ['company_id'], ondelete='CASCADE')
    op.add_column('technical_assessment_configs', sa.Column('assessment_deadline', sa.DateTime(), nullable=True))
    op.add_column('technical_assessment_configs', sa.Column('pool_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_assessment_configs', 'pool_report')
    op.drop_column('technical_assessment_configs', 'assessment_deadline')
    op.drop_constraint(None, 'company_social_auth', type_='foreignkey')
    op.create_foreign_key(op.f('company_social_auth_company_id_fkey'), 'company_social_auth', 'companies', ['company_id'], ['company_id'])
    op.drop_constraint(None, 'company_social_auth', type_='unique')
    # ### end Alembic commands ###
